# yaml 有层次，可以继承的配置文件格式
server:
  port: 80
  servlet:
    context-path: /book

#zwf:
#  info:
#    age: 18
#    name: kunling
#  root:
#    username: root
#    password: 123456
#  gfs:
#    - 高圆圆
#    - 范冰冰
#    - 二狗子

spring:
  profiles:
    active: test,dev  # 激活外部的配置，如果外部和内部配置重复，以外部为准

zwf:
  user:
    username: admin
    gfs:
      - a
      - b
      - c
